f1 = int(input('Enter result number '))
f2 = int(input('Enter result number '))
f3 = int(input('Enter result number '))
f4 = int(input('Enter result number '))
f5 = int(input('Enter result number '))
f6 = int(input('Enter result number '))
f7 = int(input('Enter result number '))
myList = [f1, f2, f3, f4, f5, f6, f7]
myList.sort()
print(myList)